name: Development Deploy

on:
  push:
    branches: ['dev']
  workflow_dispatch:

jobs:
  checkout:
    runs-on: [self-hosted, dev]
    environment: dev
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          # SENTRY_URL: https://sentry.io/
        with:
          environment: dev

  create-env:
    runs-on: [self-hosted, dev]
    environment: dev
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Set up .env file
        uses: SpicyPizza/create-envfile@v2.0.3
        with:
          envkey_DB_HOST: ${{ vars.DB_HOST }}
          envkey_DB_PORT: ${{ vars.DB_PORT }}
          envkey_DB_USER: ${{ secrets.DB_USER }}
          envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          envkey_DB_NAME: ${{ secrets.DB_NAME }}
          envkey_DB_DROP_SCHEMA: ${{ vars.DB_DROP_SCHEMA }}
          envkey_PORT: ${{ vars.PORT }}
          envkey_AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          envkey_JWT_EXP: ${{ vars.JWT_EXP }}
          envkey_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          envkey_SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

  docker-compose:
    needs: create-env
    runs-on: [self-hosted, dev]
    environment: dev
    steps:
      - name: Setup Docker Compose
        run: |
          docker compose down
          docker compose up -d

  build:
    needs: docker-compose
    runs-on: [self-hosted, dev]
    environment: dev
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/

  test:
    needs: build
    uses: ./.github/workflows/test.yml
    with:
      environment: dev
      artifact-name: build-artifacts
    secrets:
      MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
      MYSQL_DATABASE: ${{ secrets.DB_NAME }}

  deploy:
    needs: test
    uses: ./.github/workflows/reusable.yml
    with:
      runner: dev
      environment: dev
      artifact-name: build-artifacts
    secrets:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
