name: Development Deploy

on:
  push:
    branches: ['dev']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, dev]
    environment: dev
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Set up .env file
        uses: SpicyPizza/create-envfile@v2.0.3
        with:
          envkey_DB_HOST: ${{ vars.DB_HOST }}
          envkey_DB_PORT: ${{ vars.DB_PORT }}
          envkey_DB_USER: ${{ secrets.DB_USER }}
          envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          envkey_DB_NAME: ${{ secrets.DB_NAME }}
          envkey_DB_DROP_SCHEMA: ${{ vars.DB_DROP_SCHEMA }}
          envkey_PORT: ${{ vars.PORT }}
          envkey_AUTH_SECRET: ${{ secrets.AUTH_SECRET}}
          envkey_JWT_EXP: ${{ vars.JWT_EXP }}

      - name: Start database container
        run: docker compose up -d

      - name: Run tests
        run: npm run test

      - name: Build application
        run: npm run build --if-present

      - name: Install PM2 global
        run: npm install pm2@latest -g

      - name: Deploy with PM2
        run: pm2 restart dist/main.js --name=nestjs-events-api
