name: Production Deploy

on:
  workflow_dispatch:

jobs:
  checkout:
    runs-on: [self-hosted, prod]
    environment: prod
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  create-env:
    needs: checkout
    runs-on: [self-hosted, prod]
    environment: prod
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Set up .env file
        uses: SpicyPizza/create-envfile@v2.0.3
        with:
          envkey_DB_HOST: ${{ vars.DB_HOST }}
          envkey_DB_PORT: ${{ vars.DB_PORT }}
          envkey_DB_USER: ${{ secrets.DB_USER }}
          envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          envkey_DB_NAME: ${{ secrets.DB_NAME }}
          envkey_DB_DROP_SCHEMA: ${{ vars.DB_DROP_SCHEMA }}
          envkey_PORT: ${{ vars.PORT }}
          envkey_AUTH_SECRET: ${{ secrets.AUTH_SECRET}}
          envkey_JWT_EXP: ${{ vars.JWT_EXP }}

  build:
    needs: create-env
    runs-on: [self-hosted, prod]
    environment: prod
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/

  test:
    needs: build
    uses: ./.github/workflows/test.yml
    with:
      environment: prod
      artifact-name: build-artifacts
    secrets:
      MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
      MYSQL_DATABASE: ${{ secrets.DB_NAME }}

  deploy:
    needs: test
    uses: ./.github/workflows/reusable.yml
    with:
      runner: prod
      environment: prod
      artifact-name: build-artifacts
