name: Reusable Deploy

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      environment:
        required: true
        type: string
      artifact-name:
        required: false
        type: string
        default: build-artifacts

jobs:
  deploy:
    runs-on: ${{ inputs.runner }}
    environment: ${{ inputs.environment }}
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Get Code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name  }}

      - name: List files
        run: ls

      - name: Deploy with PM2
        run: |
          if pm2 describe main > /dev/null; then
            pm2 restart main --update-env
          else
            pm2 start dist/main.js --name main
          fi
