name: Reusable Deploy

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      environment:
        required: true
        type: string
      artifact-name:
        required: false
        type: string
        default: build-artifacts
    secrets:
      DB_USER:
        required: true
      DB_PASSWORD:
        required: true
      DB_NAME:
        required: true
      AUTH_SECRET:
        required: true

jobs:
  deploy:
    runs-on: ${{ inputs.runner }}
    environment: ${{ inputs.environment }}
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Get Code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}

      - name: List files
        run: ls

      - name: Deploy with PM2
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
        run: |
          if pm2 describe main > /dev/null; then
            pm2 restart main --update-env
          else
            pm2 start dist/main.js --name main
          fi
