name: Reusable Deploy

on: workflow_call

jobs:
  deploy:
    runs-on: [self-hosted, dev]
    environment: dev
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: dist/

      - name: Install PM2 globally
        run: npm install pm2@latest -g

      - name: Deploy with PM2
        run: |
          pm2 stop nestjs-events-api || true
          pm2 start dist/main.js --name=nestjs-events-api
